DI-3746 context.add_attributes()
tetrascience/ts-sdk-python pull request #43
Opened 2021-04-09 15:31 UTC by yandryianets

2021-04-09 16:27 UTC, bicca23 approved these changes

2021-04-12 23:10 UTC, chunfengd requested changes

2021-04-13 15:07 UTC, chunfengd requested changes
There are some risks in `get_next_uuid`.
- If users are doing multi thread, the saved `_next_uuid` could be changed by another thread
- `generate_uuid` is also used by `wrap_log` function, if we call `create_labels_file` first, then call a function with `wrap_log` next, and call `update_metadata_tags`, the file_id will point to a log. I know the code is controlled by us, but we may forget it in the future and it will be very hard to debug
- If we call `create_labels_file` first, but `update_metadata_tags` failed. Then if we save another file to datalake through `write_file`, the label file's file_id will points to the wrong file.

I suggest we generate `new_file_id` in `add_attributes`, and pass the new_file_id into `update_metadata_tags`.

2021-04-13 17:11 UTC, chunfengd approved these changes

2021-04-13 18:11 UTC, tlitetrasci commented
Hmm, I'm not sure I know enough context regarding the code to give a useful review

2021-04-14 07:18 UTC, merged