DE-2740: added __validate_ids method
tetrascience/ts-sdk-python pull request #66
Opened 2021-11-03 12:10 UTC by setiat

2021-11-05 16:38 UTC, mlipschultz requested changes

2021-11-05 16:38 UTC, mlipschultz commented on ts_sdk/cli/__put_cmd.py
> +        print(f"{std_err}IDS validation failed. Exiting....")
I don't think `ids_validator` ever prints to stderr, even on failed tests.  A couple quick search didn't find anything ([stderr](https://github.com/tetrascience/ts-ids-validator/search?q=stderr), [err](https://github.com/tetrascience/ts-ids-validator/search?q=err)) and a quick test locally seemed to only print stuff to stdout.

I'd be fine if you rewrote this to always print stdout and stderr to the screen (e.g. not capture it in `subprocess.run`), but maybe that's not in keeping with this project's design.

2021-11-05 16:38 UTC, mlipschultz commented on ts_sdk/cli/__put_cmd.py
> +    std_out = ids_validator_process.stdout.decode("utf-8")
FYI: If you include `text=True` in the `subprocess.run` call, you shouldn't need to decode here ([doc](https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess.stdout)).

2021-11-08 12:18 UTC, setiat commented on ts_sdk/cli/__put_cmd.py
> +        print(f"{std_err}IDS validation failed. Exiting....")
Printing `stdout` now.

2021-11-08 12:18 UTC, setiat commented on ts_sdk/cli/__put_cmd.py
> +    std_out = ids_validator_process.stdout.decode("utf-8")
fixed

2021-11-08 13:03 UTC, mlipschultz requested changes
Just one minor request, then I think it's good to merge

2021-11-08 13:03 UTC, mlipschultz commented on ts_sdk/cli/__put_cmd.py
> +        stderr=subprocess.PIPE,
Since you're not using stderr anymore, you can probably get rid of this.  However, I think it'd be better to include that in the output.  Maybe using [subprocess.STDOUT](https://docs.python.org/3/library/subprocess.html#subprocess.STDOUT) so stdout and stderr are interleaved, making it easier to see when stderr output occurred:
```suggestion
        stderr=subprocess.STDOUT,
```

2021-11-08 21:39 UTC, yandryianets commented on ts_sdk/cli/__put_cmd.py
> +    ids_validator_process = subprocess.run(
just curious, why we need to run subprocess instead of importing a function from ts-ids-validator ?

2021-11-09 09:08 UTC, setiat commented on ts_sdk/cli/__put_cmd.py
> +    ids_validator_process = subprocess.run(
No particular reason. But calling validate_ids make sense. Fixed it in the code

2021-11-09 09:08 UTC, setiat commented on ts_sdk/cli/__put_cmd.py
> +        stderr=subprocess.PIPE,
Subprocess is not called any more. 
Instead validate_ids fx will be called

2021-11-09 13:34 UTC, mlipschultz reviewed
I have two minor comments.  One to remove some unused imports and another explaining an issue I created in the ids validator repo.

Overall, I think this is good to merge, but I'd rather another reviewer give the approval since I'm not familiar enough with this repo.

2021-11-09 13:34 UTC, mlipschultz commented on ts_sdk/cli/__put_cmd.py
> +import sys
I think both of these imports are no longer used.
```suggestion
```

2021-11-09 13:34 UTC, mlipschultz commented on ts_sdk/cli/__put_cmd.py
> +    validator_args = argparse.Namespace()
It's a shame this needs to be done.  I [created a new issue](https://github.com/tetrascience/ts-ids-validator/issues/18) to make `validate_ids` easier to use in other programs.

2021-11-09 13:43 UTC, yandryianets approved these changes

2021-11-10 14:51 UTC, setiat commented on ts_sdk/cli/__put_cmd.py
> +    validator_args = argparse.Namespace()
Fixed.
ts-ids-validate v0.9.4 pushed to PyPI and required changed made to `__validate_ids()`

2021-11-10 15:26 UTC, mlipschultz requested changes
Just one minor thing, then it's good to merge in my opinion

2021-11-10 15:26 UTC, mlipschultz commented on Pipfile
> +ts-ids-validator = "*"
Can you set this to >= 0.9.4 (and in setup.py)?

2021-11-10 15:57 UTC, akohtetrascience approved these changes

2021-11-11 07:45 UTC, setiat commented on Pipfile
> +ts-ids-validator = "*"
fixed.

2021-11-11 08:48 UTC, setiat commented on ts_sdk/cli/__put_cmd.py
> +    if not ids_is_valid:
added.

2021-11-11 08:54 UTC, setiat commented
@yandryianets, @akohtetrascience 
Does merging into main, takes care of versioning and uploading the package to PyPI?

2021-11-11 09:03 UTC, yandryianets commented
> @yandryianets, @akohtetrascience Does merging into main/Travis Build, takes care of versioning and uploading the package to PyPI?

After merging to main we also have to create a new tag/release - travis then uploads a tagged build to the PyPi

2021-11-11 12:19 UTC, mlipschultz approved these changes

2021-11-11 14:10 UTC, merged