DE-2902: Artifact namespace validation
tetrascience/ts-sdk-python pull request #72
Opened 2021-12-17 11:17 UTC by cristiszabo

2021-12-17 22:23 UTC, wkopen requested changes
Looks good overall. Need unit tests and a clearer error message

2021-12-17 22:23 UTC, wkopen commented on ts_sdk/cli/__put_cmd.py
> +            "'private-<alphanumeric-and-hyphen-characters>'.")
You can say it should have `private-` as the prefix and then follow by alphanumeric or hyphens. For example, `private-a-b-c-123`. Btw, this makes me think we should not allow the last character be a hyphen. Can you add that check Cristian?

2021-12-17 22:23 UTC, wkopen commented on ts_sdk/cli/__put_cmd.py
> +def __namespace_type(arg_value: str,
Can we add some unit tests to this function?

2021-12-18 11:15 UTC, cristiszabo commented on ts_sdk/cli/__put_cmd.py
> +            "'private-<alphanumeric-and-hyphen-characters>'.")
Sure. Also, are namespaces like "private---a-b" valid?

2021-12-18 11:18 UTC, cristiszabo commented on ts_sdk/cli/__put_cmd.py
> +def __namespace_type(arg_value: str,
Yes, should I only add tests for __namespace_type or all validation functions in __put_cmd.py file?

2021-12-18 15:51 UTC, wkopen commented on ts_sdk/cli/__put_cmd.py
> +def __namespace_type(arg_value: str,
Just this function is good.

2021-12-18 15:52 UTC, wkopen commented on ts_sdk/cli/__put_cmd.py
> +            "'private-<alphanumeric-and-hyphen-characters>'.")
good point, we should only allow 1 hyphen

2021-12-20 22:53 UTC, wkopen approved these changes
Some more test cases I think you can add. Then you are good to merge.

2021-12-20 22:53 UTC, wkopen commented on __tests__/unit/test_cli_put.py
> +    "private-my--namespace"
others can be `-` at the beginning and the end of the string

2021-12-20 22:53 UTC, wkopen commented on __tests__/unit/test_cli_put.py
> +    "private-Test-Namespace"
numbers in the middle?

2021-12-21 08:19 UTC, cristiszabo commented on __tests__/unit/test_cli_put.py
> +    "private-Test-Namespace"
updated

2021-12-21 08:20 UTC, cristiszabo commented on __tests__/unit/test_cli_put.py
> +    "private-my--namespace"
updated

2021-12-21 08:27 UTC, merged