DE-3032 Ignore files
tetrascience/ts-sdk-python pull request #84
Opened 2022-03-04 20:48 UTC by VladimirShteyn

Enable ignoring files for upload using regular expressions. They may be passed in as CLI args:

```shell
ts-sdk put ... --exclude \.venv/ __pycache__
```

using the existing config file format

```json
{
  "exclude": ["\.venv/", "__pycache__]
}
```

or using environment variables,

```shell
export TS_EXCLUDE="['\.venv/', '__pycache__']"
```

Question: How do I run the integration tests? They don't pass on my machine.

2022-03-04 20:57 UTC, mlipschultz commented
It looks like you missed [`__tests__/.DS_Store`](https://github.com/tetrascience/ts-sdk-python/pull/84/files#diff-0926e16f0390a49b6ec0cf56a4956ebc75bce305c56148020c4f17076b442781)

2022-03-04 21:05 UTC, mlipschultz commented on ts_sdk/task/__util_datalake.py
> +    def __init__(self, endpoint: Optional[str]) -> None:
Thanks for taking the time to fix some broken windows while you were working on this ticket!

2022-03-04 21:18 UTC, VladimirShteyn commented
> It looks like you missed:
> 
> * [x]  [`__tests__/.DS_Store`](https://github.com/tetrascience/ts-sdk-python/pull/84/files#diff-0926e16f0390a49b6ec0cf56a4956ebc75bce305c56148020c4f17076b442781)
> * [x]  [`__tests__/unit/snapshots/.DS_Store`](https://github.com/tetrascience/ts-sdk-python/pull/84/files#diff-03466e5881d18c9527351b4e9b705ad89f905ec2887a5f17b610450d5698f305)

My bad. Fixed!

2022-03-05 11:52 UTC, yandryianets approved these changes

2022-03-05 18:37 UTC, spinwang requested changes
Maybe I missed something, but the PR seems to be different from the intent of the ticket. According to the PR, the user of the ts-sdk/SSP will have to manually add the CLI arguments such as `--exclude`, and there are no default values; I am also a little worried that using regex can be non-trivial for a data engineer, especially when it comes to escaping special characters.

Michael Lipschultz Alex Clay Vladimir Shteyn I would like to discuss if we can use a .ignore or .tsignore file following the gitignore syntax and add the files that Toby suggested to the default template.

2022-03-07 16:06 UTC, abclay reviewed
I think you have a good bunch of additions here.  It looks like it can be extended to support some of the types of file exclusions that Spin has been talking about.

2022-03-07 16:06 UTC, abclay commented on __tests__/unit/cli/test_put_cmd_helpers/test_file_filter.py
> +        Assert that a single regular expression can be added to the `FilenameFilter`.
The test here looks like it's not adding a single regex.  It's adding 2 regexes wrapped in a `FilenameFilter`

2022-03-07 19:51 UTC, VladimirShteyn commented on ts_sdk/cli/put_cmd_helpers/zip_archive_files.py
> +class ZipArchiveFiles(Iterable):
- [ ] ZipArchiveFiles  -> ZipArchiveFileSet

2022-03-07 20:01 UTC, VladimirShteyn commented on ts_sdk/cli/put_cmd_helpers/file_filter.py
> +        return self.__class__([*other.regex, *self._regex])
It seemed like a more intuitive API, kind of like how adding two numbers returns a new number. Thoughts?

2022-03-08 13:24 UTC, abclay commented on ts_sdk/cli/put_cmd_helpers/file_filter.py
> +        return self.__class__([*other.regex, *self._regex])
That makes sense.  I read the name of the function as `add a regex to this class` not `combine this class with another one and return the result`

2022-03-08 15:38 UTC, VladimirShteyn commented on ts_sdk/cli/put_cmd_helpers/file_filter.py
> +    CONFIG_FILE_EXTENSIONS = (".yaml", ".json")
OBE because config parsing was moved to the `ensure_args` function.

2022-03-08 15:42 UTC, VladimirShteyn commented on ts_sdk/cli/put_cmd_helpers/file_filter.py
> +    def from_config(cls, config: confuse.Configuration) -> "FileExcludeRegexConfig":
It should be returning `"FilenameFilter"` in quotes because at the point that the type hints are evaluated, the name `FilenameFilter` has not been defined. That will cause Python to bonk. Since Python 3.7, the quotes can be removed by doing 

```python
from __future__ import annotations
```

Quotes will not be necessary in Python 4.0.

2022-03-08 15:42 UTC, VladimirShteyn commented on ts_sdk/cli/put_cmd_helpers/file_filter.py
> +    def _update_config_from_yaml(
Fixed by moving the "exclude" config and environment variable parsing to the `ensure_args` function.

2022-03-08 15:49 UTC, VladimirShteyn commented on __tests__/unit/cli/test_put_cmd_helpers/test_file_filter.py
> +        Assert that a single regular expression can be added to the `FilenameFilter`.
Updated to 

```
"""
Assert that adding two `FilenameFilter` results in a `FilenameFilter` with
all regexes.
"""
```

2022-03-08 15:49 UTC, VladimirShteyn commented on ts_sdk/cli/__put_cmd.py
> +    Compress the folders and files specified in `args` and add to `zip_buffer`.
Fixed

2022-03-08 20:30 UTC, VladimirShteyn commented
- [ ] Update README.md with instructions for file exclusion.
- [ ] Allow setting "exclude" in the `pyproject.toml` file under `[tool.ts_sdk]`.
- [ ] Always exclude the `.git` folder (see `ensure_args`) function.

2022-03-08 21:29 UTC, VladimirShteyn commented
> Maybe I missed something, but the PR seems to be different from the intent of the ticket. According to the PR, the user of the ts-sdk/SSP will have to manually add the CLI arguments such as `--exclude`, and there are no default values; I am also a little worried that using regex can be non-trivial for a data engineer, especially when it comes to escaping special characters.

According to [this poll of the DI Team on Slack](https://tetrascience.slack.com/archives/GMTG3FDNH/p1646773373718019) looks like one third of the DI Team who responded to the poll want glob, another third want regex, and another third don't care. Since regular expressions are already implemented in this PR, let's wait for user feedback before switching to glob. Thoughts?

2022-03-08 21:30 UTC, VladimirShteyn commented on ts_sdk/cli/__put_cmd.py
> +        f"--{FilenameFilter.ARG_NAME}",
Fixed.

2022-03-09 13:45 UTC, abclay approved these changes
Just one comment about wording in the readme.  Otherwise, looks good to me!

2022-03-09 13:45 UTC, abclay commented on README.md
> +In all cases except the `ignore_ssl` and the `exclude` args, environment variable values will be overridden by the configuration file, which are overridden by values passed in via command line. All v
I would maybe reword this to something like:

```
In general, environment variable values will be overridden by the configuration file, which are overridden by values passed in via command line.

Exceptions are:
- `exclude` settings are aggregated: `"exclude": ["bar"]` in a config file and `export TS_EXCLUDE="baz qux"` would be the equivalent to passing in `--exclude bar baz qux`
- If any configuration file or environment variable sets `ignore_ssl` to `True`, its value will be `True` even if `--ignore-ssl false` is passed in.
```

2022-03-09 20:25 UTC, mlipschultz commented on README.md
> +In all cases except the `ignore_ssl` and the `exclude` args, environment variable values will be overridden by the configuration file, which are overridden by values passed in via command line. All v
I like Alex's suggestion.  Vlad's proposed change made me initially think there was no environment variable for `ignore_ssl` (although maybe because there wasn't one in the original README)

I wonder why `ignore-ssl` has a different override pattern.

2022-03-09 20:25 UTC, mlipschultz commented on README.md
> +The `exclude` arg may also be set in your repo's `pyproject.toml` file, under `[tool.ts_sdk]`. For example, to exclude the `.venv` folder, do
Is `exclude` too generic?  I'm wondering if we may want to exclude different kinds of things in the future (e.g. vendored dependencies in nodejs task scripts, or even other cli tools may want to exclude things), so having a `TS_EXCLUDE` environment variable could be confusing/abiguous for customers.  It also not as self-documenting as it could be (e.g. it doesn't explain what's being excluded or why).  Perhaps `exclude-paths` or `exclude_path_pattern` would be better?

2022-03-10 16:35 UTC, VladimirShteyn commented
@spinwang I followed up with the DI Team on Slack ([link](https://tetrascience.slack.com/archives/C9WD8SHGQ/p1646859975689879)) and looks like the preferred choice is glob. I suggest setting the default values of `--exclude` to something sensible, e.g. [the default excludes used by the builder](https://github.com/tetrascience/ts-lib-artifact-builder/blob/master/builders/task-script.builder.js#L199) and changing the filtering from regex to glob. With those changes implemented, would I get approval to merge the PR?

2022-03-10 19:24 UTC, VladimirShteyn commented on README.md
> +The `exclude` arg may also be set in your repo's `pyproject.toml` file, under `[tool.ts_sdk]`. For example, to exclude the `.venv` folder, do
I like this! `--exclude-paths` is way better.

2022-03-10 19:38 UTC, VladimirShteyn commented on README.md
> +In all cases except the `ignore_ssl` and the `exclude` args, environment variable values will be overridden by the configuration file, which are overridden by values passed in via command line. All v
- [] Update 

> @spinwang I followed up with the DI Team on Slack ([link](https://tetrascience.slack.com/archives/C9WD8SHGQ/p1646859975689879)) and looks like the preferred choice of customers is glob over regex. I suggest setting the default values of `--exclude` to something sensible, e.g. [the default excludes used by the builder](https://github.com/tetrascience/ts-lib-artifact-builder/blob/master/builders/task-script.builder.js#L199), and changing the filtering from regex to glob. With those changes implemented, would I get approval to merge the PR?

Following up from a chat with @mlipschultz and a separate one from @abclay, looks like this PR is on hold until all stakeholders finalize an implementation.

2022-03-23 14:23 UTC, closed without merging